"""create users table

Revision ID: ec33e2b20607
Revises: 
Create Date: 2025-05-16 12:17:47.336955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Foi necessário realizar estes imports
from src.domains.enums.enum_type import IntFlagEnumType
from src.domains.enums.role_type import RoleType

# revision identifiers, used by Alembic.
revision: str = 'ec33e2b20607'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('roles', IntFlagEnumType(RoleType), nullable=False), # Foi necessário ajustar esta linha
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
