services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy # Funciona em conjunto com HealthCheck do banco, apenas sobe API quando banco estiver iniciado
    environment:
      - DATABASE_URL=postgresql+psycopg://dbadmin:Wolfros!#$123@db:5432/widgets_db
      # - DATABASE_URL=${DATABASE_URL} # Recomendado para produção
    networks:
      - app_network
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: Wolfros!#$123
      POSTGRES_DB: widgets_db
    ports:
      - 5435:5432 # Caso haja dois bancos (um na máquina e outro no container, é necessário alterar a porta externa, da esquerda para não haver conflito)
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck: # HealthCheck do banco
      test:
        [
          "CMD-SHELL",
          "timeout 1 bash -c 'cat < /dev/null > /dev/tcp/localhost/5432' || exit 1", # Atenção: Porta precisa ser a mesma do banco de dados (nesse caso a 5432, porta interna do postgres)
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge